config/routes.rb
Rails.application.routes.draw do
  get 'subscription/create'

  namespace :admin do
    resources :admin_users
    resources :posts
    resources :subscriptions

    root to: "admin_users#index"
  end

  devise_for :admin_users
  resources :subscriptions
  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin, :authenticate_admin_user!

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/subscriptions_controller.rb
module Admin
  class SubscriptionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Subscription.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Subscription.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @subscription = Subscription.new
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(subscription_params)

    if @subscription.save
      redirect_to root_path, flash: { success: 'Te estaremos Enviando las novedades!' }
    else
      redirect_to root_path, warning: 'Por Favor digita una dirección válida'
    end
  end

  private
    def subscription_params
      params.require(:subscription).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/home/index.html.erb
<div class="intro-img">
    <div class="overlay">
        <div class="container text-white">
            <h1>Ministerio Amigos de Jesús y María</h1>
            <table align="center">
                <tr>
                    <td>Dejen a los niños, y no se los impidan que vengan a mí, porque de los que son como éstos es el Reino de los cielos</td>
                </tr>
                <tr>
                    <td class="q-source">Mateo 19,14</td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="home-block bg-light-green text-white">
    <div class="container">
        <h2>Mantente Informado</h2>
        <%= form_for(@subscription) do |f| %>
            <% if @subscription.errors.any? %>
                <div id="error_explanation">
                <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this product from being saved:</h2>
                <ul>
                <% @subscription.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
                </ul>
                </div>
            <% end %>
        <div class="form-group">
            <%= f.text_field :email, :class => 'form-control', :placeholder => "Digita tu Correo", aria: { describedby: "emailHelp" }%>
            <small id="emailHelp" class="form-text text-muted">Nunca corpartiríamos tu correo con nadie más</small>
        </div>
        <div class="actions">
        <%= f.submit 'Enviar', class: 'btn btn-primary '%>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ministerio de Jesus y Maria</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav id="menu" class="navbar navbar-inverse navbar-toggleable-md fixed-top bg-primary">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">MAJM</a>
      <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Quienes Somos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contacto</a>
          </li>
          <% if admin_user_signed_in? %>
          <li class="nav-item">
          <%= link_to('Logout', destroy_admin_user_session_path, :method => :delete, :class => "nav-link" ) %>        
          </li>
          <% else %>
            <li class="nav-item">
            <%= link_to('Login', new_admin_user_session_path, :class => "nav-link" )  %>  
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container notices">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      </div>
      <%= yield %>
  </body>
</html>

app/views/subscription/create.html.erb
<h1>Subscription#create</h1>
<p>Find me in app/views/subscription/create.html.erb</p>